### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by rvirnau** [jethornton/7i96#11]
getting below:

bobby@linuxcnc:~$ sudo gdebi python3-c7i96_1.2.2-1_all.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Mesa configuration tool for 7i96
 # Mesa 7i96 Configuration Tool
 .
 The 7i96 Configuration Tool will create a complete configuration from scratch.
 .
 Read in the ini configuration file for changes.
 .
 You can create a configuration then run it with the Axis GUI and use
 Machine > Calibration to tune each axis. Save the values to the ini file and
 next time you run the 7i96 Configuration Tool it will read the values from the
 ini file.
 .
 See the [documentation](https://jethornton.github.io/7i96/) for installation and
 usage instructions.
 .
 Note: The master branch might be broken from time to time while I improve the
 configuration tool. The 0.1.5 branch should be stable.
Do you want to install the software package? [y/N]:y
(Reading database ... 187412 files and directories currently installed.)
Preparing to unpack python3-c7i96_1.2.2-1_all.deb ...
Unpacking python3-c7i96 (1.2.2-1) over (1.2.2-1) ...
Setting up python3-c7i96 (1.2.2-1) ...
  File "/usr/lib/python3/dist-packages/c7i96/c7i96.py", line 307
    self.maxVelocityLbl.setText(f'{fpm} IPM')
                                           ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/c7i96/card-broken.py", line 10
    command = f"mesaflash --device 7i96 --addr {ipAddress} --readhmid"
                                                                     ^
SyntaxError: invalid syntax

dpkg: error processing package python3-c7i96 (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 python3-c7i96

**Comment by jethornton** [comment]
Use the latest deb, that must be an old one.

JT
