### ISSUE TITLE
Install fail with Gdebi

### ISSUE THREAD

**Issue by MartynT50** [jethornton/7i96#15]
Lintian check failed with the following issues:
"E: 7i96: description-starts-with-package-name
W: 7i96: desktop-entry-lacks-main-category usr/share/applications/7i96 Configurator.desktop

Lintian finished with exit status 1"

Installing in terminal with dpkg installs OK but application in the CNC folder is named "Something". When opened shows title as version 1.2.6

**Comment by jethornton** [comment]
The current version is 1.3.0
