### ISSUE TITLE
io.hal parameter naming error

### ISSUE THREAD

**Issue by vegaServer** [jethornton/7i96#16]
The wizard outputs GPIO hal parameter like this:
```
net both-limit-joint-0 joint.0.neg-lim-sw-in <= hm2_7i96.0.gpio.01.in
```
but it seems that the number of pins need to be in 3 decimal placed or LinuxCNC will not able to find this parameter. For example this works in LinuxCNC 2.8.1 for me:
```
net both-limit-joint-0 joint.0.neg-lim-sw-in <= hm2_7i96.0.gpio.001.in
```

**Comment by jethornton** [comment]
Thanks for the feedback.
