### ISSUE TITLE
MIssing Board Configuration

### ISSUE THREAD

**Issue by vegaServer** [jethornton/7i96#18]
In the latest version 1.3.2, the drop-down list of Board Configuration cannot be clicked. In 1.3.1 it works fine. Maybe related to the commit 4e4223bb8297bd6c97b45663d9133a1f6043e782 in `src/lib7i96/buildcombos.py`.

I have double-check that it is 1.3.2, not 1.3.1 as shown in title bar.
![2021-06-17_15-31](https://user-images.githubusercontent.com/67610433/122351829-1c739600-cf81-11eb-9b50-cb95c5df641f.png)

**Comment by jethornton** [comment]
I did quite a bit of rework to the code and I spot two things to fix.

Thanks
JT

**Comment by jethornton** [comment]
I'm still trying to decide what I want to do there. That whole section is only to help define the loadrt hostmot2 in the main hal file.

JT

**Comment by vegaServer** [comment]
Maybe creating a list of existed .bit files in lib for selection and a small instruction manpage printed in the sidebar that describe the syntax of file name is enough. Something like:
```
Filename: [MODEL]d_[DESCR].bit
[MODEL]:
	7i96
	7i76
	..
	.
[DESCR]:
	1pwm	One pwm generator
	inmd	..
	pktd         ..
```
