### ISSUE TITLE
QT Designer Layout

### ISSUE THREAD

**Issue by jethornton** [jethornton/7i96#2]
I'm not sure how to do the layout for the Axis Joint n tabs so if you get some spare time I could use some hints.

**Comment by KurtJacobson** [comment]
@jethornton ok, I will look at it!

**Comment by KurtJacobson** [comment]
Does this seem OK? I only did the Joint 0 tab for now as an example.

![7i96-joint_tab_layout](https://user-images.githubusercontent.com/19997275/43597684-d7697cee-9650-11e8-8b51-9062f3d18e2d.png)

**Comment by jethornton** [comment]
That looks real nice go ahead and push that so I can see what you did.

**Comment by jethornton** [comment]
I used QLineEdit so the user didn't think they had to put 4 decimal places and it does not limit the decimal places.

**Comment by jethornton** [comment]
When I run it the Maximum Limit label on joint 0 is on one line but the rest of the tabs it's on two lines. I'm not sure what's going on as the ui shows them all on two lines.

**Comment by jethornton** [comment]
There seems to be something odd with the joint0 axis combobox, it's wider than the rest.

**Comment by KurtJacobson** [comment]
Yes, I encountered both of those, and did not see how to resolve them right away. If you set the "current tab index" in designer to 1 you will see that both problems go away. I am I think it might have something to do with which widgets get the default focus ...

**Comment by jethornton** [comment]
Really weird lol. 
Thanks
