### ISSUE TITLE
 from m7i96.7i96 import main                ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by snelweg** [jethornton/7i96#6]
Wanted to try your configtool, does not work for me. What am I doing wrong?

```
ton@LinuxCNC-MESA:~$ 7i96
  File "/usr/local/bin/7i96", line 7
    from m7i96.7i96 import main
               ^
SyntaxError: invalid syntax
```

Debian 9.8 machine
`ton@LinuxCNC-MESA:~$ cat /etc/debian_version 
9.8`

Python version
`ton@LinuxCNC-MESA:~$ python --version
Python 3.5.3`

**Comment by jethornton** [comment]
Hmm, I'm not sure I have here

`john@qtpyvcp:~$ cat /etc/debian_version
9.8
john@qtpyvcp:~$ python --version
Python 2.7.13
`

but it is programmed to run with python3
`john@qtpyvcp:~$ python3 --version
Python 3.5.3
`
I don't get that error on Debian 9 or LinuxMint 19.3

Is your system not a normal Debian install? Just pulling straws so to speak...

JT

**Comment by snelweg** [comment]
Hi JT,
Thanks for taking the time and responding.

I tried both python versions 2.7.3 and version 3.5.3 on my Debian machine.
It is a stock Debian distribution, the exact one that is needed to get LinuxCNC and a Mesa card up and running. So nothing special about that.

Ans yes, I used that Github page to install. It all went smoothly after I upgraded the old pip version to the most current.
I will try this later today, I am not at the machine right now: https://stackoverflow.com/questions/15417415/python-syntax-error-with-import

Thanks again for your efforts, they are greatly appreciated!

**Comment by snelweg** [comment]
> I will try this later today, I am not at the machine right now: https://stackoverflow.com/questions/15417415/python-syntax-error-with-import

Did not work either.

**Comment by snelweg** [comment]
git it working!

I used the clone command, changed into the m7i96 dir and started 7i96.py from there. Now it all works!
Will let you know if it makes a workable config for me.
Thanks for all your efforts!

**Comment by snelweg** [comment]
git it working!

I used the clone command, changed into the m7i96 dir and started 7i96.py from there. Now it all works!
Will let you know if it makes a workable config for me.
Thanks for all your efforts!

**Comment by OPatrick** [comment]
Hello,
Got same problem. When doing snelweg solution, I cannot save the config, neither by "save" nor "save as".
