### ISSUE TITLE
HAL file syntax

### ISSUE THREAD

**Issue by phillc54** [jethornton/7i96#7]
The following line appears in the HAL file:
loadrt [HOSTMOT2](DRIVER) board_ip=[HOSTMOT2](IPADDRESS) config="num_encoders=[HOSTMOT2](ENCODERS)num_stepgens=[HOSTMOT2](STEPGENS)"sserial_port_0=[HOSTMOT2](SSERIAL_PORT)

There needs to be a space in front of num_stepgens and the double quote in front of sserialPort should be moved to the end of the line and replaced with a space.

**Comment by jethornton** [comment]
Not sure why I didn't get and email when you posted this...

JT

**Comment by phillc54** [comment]
I had forgotten about this...
It seems to work OK in normal circumstances but Twopass doesn't like it.

**Comment by jethornton** [comment]
Fixed typo and missing space
