### ISSUE TITLE
FileNotFoundError: [Errno 2] 'mesaflash64'

### ISSUE THREAD

**Issue by Bouni** [jethornton/7i96#9]
Hi,

I just installed 7i96 as described on a Debian 10 Buster.
It works but crashes if I click Read in the firmware section.
I guessed that I don't have mesaflash installed, which was the case but the issue is still present after installing mesaflash from the git repo (which results in /usr/bin/mesaflash).
Then I realized that you ship mesaflash32 and mesaflash64 binaries with the installation.

I'm not sure but I think they should both be copied to .local/bin on installation, right?

If I execute the pip3 installation with -vvv I see:
```
  adding 'home/miller/.local/bin/mesaflash32'
  adding 'home/miller/.local/bin/mesaflash64'
```
but after the Installation is complete `ls -la .local/bin` gives me just
```
insgesamt 12
drwxr-xr-x 2 miller miller 4096 Mai 11 15:42 .
drwxr-xr-x 5 miller miller 4096 Mai 11 15:42 ..
-rwxr-xr-x 1 miller miller  213 Mai 11 15:42 7i96
```

Any ideas why the two files are not copied to the right location?

**Comment by broose-goose** [comment]
If ~/.local/bin is in your path, this should work.

They way I did it was to install mesaflash [from the source](https://github.com/LinuxCNC/mesaflash), and then created a symbolic link between mesaflash and mesaflash64

`
$ ln /bin/mesaflash /bin/mesaflash64
`

**Comment by jethornton** [comment]
Changes have been made to use the LinuxCNC hosted mesaflash instead of my local copy
